### ISSUE TITLE
question about the loader

### ISSUE THREAD

**Issue by LiorSaadon** [DatenMetzgerX/webpack-angular-translate#15]
Hi,
my project uses StaticFileLoader from "angular-translate-loader-static-files"

_the configuration looks like this:_

```
    $translateProvider.useStaticFilesLoader({
        prefix: '/common/assets/localization/strings_',
        suffix: '.json'
    });
    $translateProvider.preferredLanguage('en_US');
```

_the original file (strings_en_US.json) looks like this:_

```
{
    "home" :{
        "change": "Change name",
        "random": "Random name"
    }
}
```

_html looks like:_
```
<button class="btn btn-primary" ng-click="home.changeName()">{{"home.change" | translate}}</button>
<button class="btn btn-danger" ng-click="home.randomName()" translate="home.random"></button>
```

_when i build my project the loader creates my "translations.json" file and it looks like this:_
```
{
	"home.change": "home.change",
	"home.random": "home.random"
}
```

_I expected to see something like this:_
```
{
	"home.change": "Change",
	"home.random": "Random"
}
```

is there a way to fix that or i got it wrong?

**Comment by DatenMetzgerX** [comment]
Hy Lior

Actually I dont undersrand what you intend  to do. What transformation are
you expecting from the plugin?

My response will be delayed as I'm at my vacations. But I will be back next
friday. But please provide some more details about your goal.

Cheers,
Micha
Am 08.02.2016 1:40 nachm. schrieb "Lior Saadon" <notifications@github.com>:

**Comment by LiorSaadon** [comment]
Hi Micha,

My question is about the loader, i'm not sure i understand when it will work and how.
I expect the loader to:
1. Go over my *.js and *.html files and look for strings to translate.
2. use the "$translateProvider.useStaticFilesLoader" to load and then concat all the json translation files into one big file named "translations.json"
3. replace the templates in my *.js and *.html with the translated strings

**Comment by DatenMetzgerX** [comment]
Hy Lior

Thats not how the plugin is intended to work. I think what you'r expecting is compile time translation of all strings in the html and javascript, is that right? My question is then, what is the benefit of using angular-translate at all if you need a different angular application (at least a different deliverable) for each language that you support?

The idea of the plugin is different. The plugin will create the string_en_US.json (or what ever your default language is) by searching for all used strings that are translated by angular-translate at runtime. This file can then be loaded by the static file loader for your default language. But at runtime angular-translate is still needed to perform the actual translation...

**Comment by LiorSaadon** [comment]
Hi Micha,
Thanks for the clarification, you can close this issue.
